//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.WinchController
{
    public class MDepth : Message
    {
        public const string RosMessageName = "winch_controller/Depth";

        public float depth;

        public MDepth()
        {
            this.depth = 0.0f;
        }

        public MDepth(float depth)
        {
            this.depth = depth;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.depth));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.depth = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MDepth: " +
            "\ndepth: " + depth.ToString();
        }
    }
}
