//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.WinchController
{
    public class MSetVelocityRequest : Message
    {
        public const string RosMessageName = "winch_controller/SetVelocity";

        public float vel;

        public MSetVelocityRequest()
        {
            this.vel = 0.0f;
        }

        public MSetVelocityRequest(float vel)
        {
            this.vel = vel;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.vel));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.vel = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MSetVelocityRequest: " +
            "\nvel: " + vel.ToString();
        }
    }
}
