//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.WinchController
{
    public class MWinchTriggerResponse : Message
    {
        public const string RosMessageName = "winch_controller/WinchTrigger";

        public bool result;

        public MWinchTriggerResponse()
        {
            this.result = false;
        }

        public MWinchTriggerResponse(bool result)
        {
            this.result = result;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.result));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.result = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MWinchTriggerResponse: " +
            "\nresult: " + result.ToString();
        }
    }
}
